Bootstrap: docker
From: alpine:3.9

%files
   doubler.sh /bin/

%post
    # The script needs bash
    apk update
    apk upgrade
    apk add bash
    # Ensure it's executable
    chmod +x /bin/doubler.sh    

%environment
    export LC_ALL=en_US.UTF-8

%runscript
    /bin/doubler.sh
